### ISSUE TITLE
A new business rule is required

### ISSUE THREAD

**Issue by cmonsalvec** [LeonardoGoPe/lSII_WORKSHOP2_CAREAPP#1]
**Is your feature request related to a problem? Please describe.**

This feature is not related to a problem. It is related to a new policy of the organization. 

Based on the impact of the pandemic in the 2020 results, the board of the company has approved a new business rule (policy) beginning january 2021, that needs to be included in our product. 

**Describe the solution you'd like**

The new business rule establishes: If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.

Therefore, we ask you to modify the premium calculation adding this new rule. 

**Describe alternatives you've considered**

There is no alternative to be considered.

**Additional context**

I will provide you with more information if needed

Best regards,

**Comment by tiomaldy** [comment]
We going to check and add the new parameters.


Best regards,

**Comment by tiomaldy** [comment]
@cmonsalvec  Dear Customer ,
This is the analysis of the plan that the team make ,we wish you like and hope you accept it

[Analisis del problema.docx](https://github.com/LeonardoGoPe/lSII_WORKSHOP2_CAREAPP/files/5846445/Analisis.del.problema.docx)

**Comment by cmonsalvec** [comment]
Dear @tiomaldy ,

Thanks, but sorry, I can´t read spanish

Best regards

**Comment by tiomaldy** [comment]
@cmonsalvec 
Our mistake i send you the new document ,translated by @JordyM97   our specialist in languages
[Analysis.docx](https://github.com/LeonardoGoPe/lSII_WORKSHOP2_CAREAPP/files/5846493/Analysis.docx)

**Comment by cmonsalvec** [comment]
Dear @tiomaldy

**Comment by tiomaldy** [comment]
@cmonsalvec  Dear customer ,
We solve the issue and can you check here 
https://github.com/LeonardoGoPe/lSII_WORKSHOP2_CAREAPP/blob/0651da13aad645c477504d22d6f2f6a419250433/src/main/java/ec/edu/espol/workshops/second/CarInsurance.java#L16-L18

**Comment by tiomaldy** [comment]
@cmonsalvec Dear customer,
Here i send you the System Testing that we perfom
[Issues Management - System Testing -Careapp (1).docx](https://github.com/LeonardoGoPe/lSII_WORKSHOP2_CAREAPP/files/5846920/Issues.Management.-.System.Testing.-Careapp.1.docx)

**Comment by cmonsalvec** [comment]
Great, thanks a lot. ¿Are we going to agree with some acceptance testing?

**Comment by tiomaldy** [comment]
Dear @cmonsalvec 
What need to be included in the acceptance testing ?

**Comment by tiomaldy** [comment]
@cmonsalvec Dear customer,
In the last document our team send you the acceptance testing.

**Comment by tiomaldy** [comment]
@cmonsalvec Dear customer,
Could you please check the new code,you just need to execute the main code and make the test you want and if you want to check the unit test you should run the CarInsuranceTest.
We wait for the finall acceptance and if you like the solution that we provide

Best regards,

**Comment by cmonsalvec** [comment]
Dear @tiomaldy,

Sorry, I am not so good with this, can you tell me where is the code and how I can use it? Thanks

**Comment by tiomaldy** [comment]
@cmonsalvec Dear customer.
Is in the IssuesManagement branch, then go to the src folder, then to main/java/ec/edu/espol/workshops/second and there you will find the code
CarInsurance is the code with the validation that you indicated us
CarInsuranceTest is the unit tests performed according to the System Tests file.
Main is the one to run to check that the results are as expected.

**Comment by tiomaldy** [comment]
You can find here the new code here too @cmonsalvec 
https://github.com/LeonardoGoPe/lSII_WORKSHOP2_CAREAPP/blob/6015b71572a763bf7fc4a5982aee44fc40c82c5f/src/main/java/ec/edu/espol/workshops/second/CarInsurance.java#L16-L18

**Comment by cmonsalvec** [comment]
Great, thanks @tiomaldy, I've tried it and everythink looks ok. Good job.
